
---
# This workflow integrates QwietAI preZero with GitHub
# Visit https://docs.shiftleft.io for help
name: QwietAI_preZero

on:
  push:
    branches:
      - main

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download QwietAI CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    # QwietAI requires Java 1.8. Post the package step override the version
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    # the sl analyze command below supports multilanguage detection/scanning. In addition, the container being used is pointing to Qwiets Registry and should be removed or edited for customers info
    - name: NextGen Static Analysis
      #The 1st run example shows how to execute scan with an app name defined, if app name is not added san will automtically be named the repo name. For other options please reference the UserGuide. 
      #run: ${GITHUB_WORKSPACE}/sl analyze --strict --wait --app Qwiet-Java-GH --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --container 18fgsa/s3-resource
      run: ${GITHUB_WORKSPACE}/sl analyze --strict --wait --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} 
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_HOST: www.shiftleft.io
        SHIFTLEFT_GRPC_TELEMETRY_HOST: telemetry.shiftleft.io:443
        SHIFTLEFT_GRPC_API_HOST: api.shiftleft.io:443

  
